// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWG-Id1ck_kDkOmd_RRTbeeqDPZy50CO4',
    appId: '1:541497990875:web:8c9825fcf3bdb759f1f6fe',
    messagingSenderId: '541497990875',
    projectId: 'chatsystem-5ff83',
    authDomain: 'chatsystem-5ff83.firebaseapp.com',
    storageBucket: 'chatsystem-5ff83.appspot.com',
    measurementId: 'G-GMMTZTYBVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2YwkRBtrXB3OHNK0usUHBuPm07YT-IwQ',
    appId: '1:541497990875:android:811903cf77567deaf1f6fe',
    messagingSenderId: '541497990875',
    projectId: 'chatsystem-5ff83',
    storageBucket: 'chatsystem-5ff83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0yn3Jz4OMkSUdB6nz3tXAyegj1IBQ6-I',
    appId: '1:541497990875:ios:d8455ecad0dda6c8f1f6fe',
    messagingSenderId: '541497990875',
    projectId: 'chatsystem-5ff83',
    storageBucket: 'chatsystem-5ff83.appspot.com',
    iosBundleId: 'com.example.chatSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0yn3Jz4OMkSUdB6nz3tXAyegj1IBQ6-I',
    appId: '1:541497990875:ios:066bcc2b9112c734f1f6fe',
    messagingSenderId: '541497990875',
    projectId: 'chatsystem-5ff83',
    storageBucket: 'chatsystem-5ff83.appspot.com',
    iosBundleId: 'com.example.chatSystem.RunnerTests',
  );
}
